Repository inslog94/FavSpot, pull requests merged in 2023-10, with the labels that each got.

#129 🩹 저장소 관련 재설정에 따른 image 경로 변경
  everyplace/board/views.py
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/tagged_board_list.html
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/data.js
  frontend/assets/js/maps/pinDetail.js
  frontend/assets/js/request/content.js
  frontend/assets/js/util/boardSlide.js
  frontend/assets/js/util/footer.js
  frontend/assets/js/util/header.js
  frontend/assets/js/util/placeInfo.js
  frontend/index.html
Labels: FE, BE

#130 [FE] [BE] Board 앱 관련 문제 해결, API명세서에 url-method 제거 위한 작업
  everyplace/app/settings.py
  everyplace/board/excluded_path.py
  everyplace/board/views.py
  everyplace/user/serializers.py
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/tagged_board_list.html
  frontend/assets/js/maps/boardDetail.js
Labels: FE, BE

#134 핀이 저장되지 않은 장소의 상세보기 페이지에서의 핀 저장 기능 추가, 핀 저장 관련 전반적인 에러 수정
  everyplace/pin/views.py
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/maps/pinDetail.js
  frontend/assets/js/request/content.js
  frontend/assets/js/util/placeInfo.js
Labels: FE, BE

#135 [FE] [BE] Board 정렬 기능 추가, 간편 보드 최초 생성 시 보드 목록 조회 가능하도록 수정 및 자잘한 에러수정
  everyplace/user/serializers.py
  frontend/assets/css/index.css
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/index.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/util/boardSlide.js
Labels: FE, BE

#138 UI 개선 작업 완료
  frontend/assets/css/index.css
  frontend/assets/css/map.css
  frontend/assets/css/modal.css
  frontend/assets/css/template/style.css
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/tagged_board_list.html
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/js/maps/pin.js
  frontend/assets/js/template/mega-menu/mega_menu.js
  frontend/assets/js/util/boardSlide.js
  frontend/assets/js/util/footer.js
  frontend/assets/js/util/pinDetailModal.js
Labels: FE

#139 알림 리스트 페이지에서 체크박스를 통한 다중 읽음처리, 삭제 기능 및 관련 UI 추가
  frontend/assets/html/notification.html
Labels: FE

#141 전 페이지 알림 관련 요청 축소 및 리팩토링
  everyplace/notification/consumers.py
  frontend/assets/js/maps/websocket.js
  frontend/assets/js/request/content.js
  frontend/assets/js/util/header.js
Labels: FE, BE

#142 [FE] [BE] 보드 검색 결과에 대한 정렬 기능 추가 및 자잘한 에러 수정
  everyplace/board/views.py
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/index.js
  frontend/assets/js/request/content.js
Labels: FE, BE

#143 핀 상세보기 모달 예외처리 및 UI 일부 수정
  frontend/assets/html/board_detail.html
  frontend/assets/js/maps/pinDetail.js
  frontend/assets/js/util/pinDetailModal.js
Labels: FE

#146 [FE] [BE] 401, 404 에러 처리 및 유저 정보 페이지 및 파생 페이지 전반적인 수정, 보드 태그 관련 에러 해결
  everyplace/app/middleware.py
  everyplace/app/settings.py
  everyplace/board/urls.py
  everyplace/board/views.py
  frontend/assets/css/map.css
  frontend/assets/html/404.html
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/img/404.png
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/index.js
  frontend/assets/js/util/customFetch.js
  frontend/assets/js/util/header.js
Labels: FE, BE

#148 핀 코멘트 관련 기능 및 핀 코멘트 목록 페이지 전면 개편
  everyplace/pin/serializers.py
  everyplace/pin/urls.py
  everyplace/pin/views.py
  frontend/assets/css/modal.css
  frontend/assets/html/pin_list.html
  frontend/assets/js/maps/pinDetail.js
  frontend/assets/js/util/getPlaceInfo.js
  frontend/assets/js/util/pinDetailModal.js
  frontend/assets/js/util/placeInfo.js
  frontend/assets/js/util/setPlaceInfo.js
Labels: FE, BE

#150 Index Page 지도 깨짐 현상 수정
  frontend/assets/css/index.css
  frontend/assets/js/maps/index.js
  frontend/assets/js/util/responsive.js
Labels: FE

#152 보드 간편 생성 관련 사용자 경험 개선
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/request/content.js
Labels: FE

#154 장소 검색 시 특정 장소들의 썸네일 이미지가 디폴트 이미지로 설정되는 문제 해결
  frontend/assets/js/maps/pin.js
  frontend/assets/js/util/getPlaceInfo.js
Labels: FE

#156 지도 우측 상단 옵션값(지도/스카이뷰, 확대/축소)이 잘려 보이는 문제 해결
  frontend/assets/js/maps/event.js
Labels: FE

#158 프로필 수정 페이지 UI 개선 완료
  everyplace/user/views.py
  frontend/assets/html/profile_edit.html
Labels: FE, BE

#160 병합 과정에서 버튼 및 이미지 CSS 수정
  frontend/assets/css/pin-list.css
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
Labels: FE

#162 모든 HTML 파일에서 공통적으로 사용되는 CSS 및 JS 파일 분리 완료
  frontend/assets/css/board-detail.css
  frontend/assets/css/board-list.css
  frontend/assets/css/template/bootstrap.css
  frontend/assets/css/template/style.css
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/tagged_board_list.html
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/follower.js
  frontend/assets/js/maps/following.js
  frontend/assets/js/maps/login.js
  frontend/assets/js/maps/notifications.js
  frontend/assets/js/maps/pinList.js
  frontend/assets/js/maps/profileEdit.js
  frontend/assets/js/maps/signup.js
  frontend/assets/js/maps/taggedBoard.js
  frontend/assets/js/maps/userInfo.js
  frontend/assets/js/maps/userLikedBoard.js
  frontend/assets/js/maps/userTaggedBoard.js
  frontend/assets/js/template/custom.js
  frontend/assets/js/util/header.js
  frontend/assets/js/util/script.js
  frontend/index.html
Labels: FE

#163 [BE] 미들웨어 수정 및 삭제
  everyplace/app/middleware.py
  everyplace/app/settings.py
Labels: BE

#165 콘솔창에 지속적으로 이벤트 리스너 에러 메시지가 발생하는 문제 해결
  frontend/assets/js/maps/event.js
Labels: FE

#166 핀 코멘트 관련 최적화, 핀 상세보기 모달 및 보드 상세보기 페이지 UI수정
  everyplace/user/serializers.py
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/pinDetail.js
Labels: FE, BE

#167 [FE] 사용하지 않는 이미지 경로 제거 및 자물쇠 아이콘 css 수정, Profile Edit 버튼 변경, Pin Contents 문구 수정
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/user_info.html
  frontend/assets/js/util/boardSlide.js
  frontend/assets/js/util/pinDetailModal.js
Labels: FE

#171 배포 전 테스트 중 발견한 이미지 관련 오류 수정
  frontend/assets/js/boardDetail.js
  frontend/assets/js/util/header.js
  frontend/assets/js/util/pinDetailModal.js
Labels: FE

#176 404 Not Found Page 생성 및 설정
  config/nginx/nginx.conf
  src/frontend/assets/html/404.html
Labels: FE

#178 배포 이후 발견한 문제 해결 및 개선사항
  src/backend/app/middleware.py
  src/backend/app/settings.py
  src/backend/user/models.py
  src/frontend/assets/js/board.js
  src/frontend/assets/js/boardDetail.js
  src/frontend/assets/js/content.js
  src/frontend/assets/js/event.js
  src/frontend/assets/js/follower.js
  src/frontend/assets/js/login.js
  src/frontend/assets/js/notifications.js
  src/frontend/assets/js/pin.js
  src/frontend/assets/js/pinDetail.js
  src/frontend/assets/js/pinList.js
  src/frontend/assets/js/profileEdit.js
  src/frontend/assets/js/signup.js
  src/frontend/assets/js/userLikedBoard.js
  src/frontend/assets/js/userTaggedBoard.js
  src/frontend/assets/js/util/boardSlide.js
  src/frontend/assets/js/util/customFetch.js
  src/frontend/assets/js/util/header.js
  src/frontend/assets/js/util/staticMap.js
  src/frontend/assets/js/websocket.js
Labels: FE, BE

#180 핀 간편저장 관련 에러 해결 및 개선
  src/backend/board/views.py
  src/backend/pin/urls.py
  src/backend/pin/views.py
  src/frontend/assets/html/board_detail.html
  src/frontend/assets/js/content.js
  src/frontend/assets/js/pin.js
Labels: FE, BE

#182 HTTPS 설정 완료
  config/nginx/nginx.conf
  config/requirements.txt
  docker-compose.yml
  src/backend/notification/routing.py
  src/frontend/assets/html/login.html
  src/frontend/assets/html/signup.html
  src/frontend/assets/js/boardDetail.js
  src/frontend/assets/js/content.js
  src/frontend/assets/js/data.js
  src/frontend/assets/js/event.js
  src/frontend/assets/js/follower.js
  src/frontend/assets/js/following.js
  src/frontend/assets/js/login.js
  src/frontend/assets/js/notifications.js
  src/frontend/assets/js/pin.js
  src/frontend/assets/js/pinList.js
  src/frontend/assets/js/profileEdit.js
  src/frontend/assets/js/signup.js
  src/frontend/assets/js/taggedBoard.js
  src/frontend/assets/js/userInfo.js
  src/frontend/assets/js/userLikedBoard.js
  src/frontend/assets/js/userTaggedBoard.js
  src/frontend/assets/js/util/header.js
  src/frontend/assets/js/websocket.js
Labels: FE, BE

#183 배포 이후 발견한 웹소켓 연결 문제 해결 및 UI 수정
  src/backend/notification/routing.py
  src/frontend/assets/js/boardDetail.js
  src/frontend/assets/js/util/pinDetailModal.js
  src/frontend/assets/js/websocket.js
Labels: FE, BE

#185 보드 검색시 검색 키워드 뿐만 아니라 검색 결과 장소명 목록으로도 검색되도록 개선
  src/backend/board/views.py
  src/frontend/assets/js/pin.js
  src/frontend/assets/js/search.js
Labels: FE, BE
