Repository inslog94/FavSpot, pull requests merged in 2023-09, with the labels that each got.

#59 프론트 연결 시 문제되는 Pin 관련 부분의 url, view, serializer 수정
  everyplace/pin/paginations.py
  everyplace/pin/serializers.py
  everyplace/pin/urls.py
  everyplace/pin/views.py
Labels: BE

#62 [FE] 핀 간편 생성 기능 수정 완료
  frontend/assets/css/map.css
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/data.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/request/content.js
  frontend/index.html
Labels: FE

#60 [BE] Board 프론트와 유연하게 연결 위한 전체적인 코드 수정
  everyplace/board/serializers.py
  everyplace/board/views.py
Labels: BE

#65 [FE] 메인 페이지 보드 썸네일
  frontend/assets/css/map.css
  frontend/assets/css/modal.css
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/data.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/map.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/maps/pinDetail.js
  frontend/assets/js/request/content.js
  frontend/index.html
Labels: FE

#68 Pin 상세보기 UI 구현
  everyplace/pin/views.py
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/data.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/map.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/maps/pinDetail.js
  frontend/index.html
Labels: FE, BE

#69 [BE] Board 상세보기와 수정 페이지 UI 구현
  everyplace/board/views.py
  everyplace/pin/serializers.py
  frontend/assets/css/style.css
  frontend/assets/html/board_detail.html
  frontend/assets/js/maps/boardDetail.js
Labels: FE, BE

#70 User 관련 프론트 페이지 구현
  everyplace/user/models.py
  everyplace/user/serializers.py
  everyplace/user/views.py
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/user_info.html
Labels: FE

#72 연결 작업 시 발생한 문제 수정
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/user_info.html
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/data.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/pinDetail.js
  frontend/index.html
Labels: FE

#73 삭제된 보드 내역이 보이는 문제 수정
  everyplace/user/views.py
Labels: BE

#75 [BE] 연결 작업 시 발생한 에러 수정(board), pre-loader파일 경로 수정
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/user_info.html
  frontend/assets/img/pre-loader/loader-03.svg
  frontend/index.html
Labels: FE

#77 [FE] 메인 페이지 header에서 login, signup 버튼 경로 수정
  frontend/assets/js/maps/event.js
Labels: FE

#78 [BE] board 전체 조회 시 로그인하지 않은 사용자도 조회 가능
  everyplace/board/views.py
Labels: BE

#79 🩹 [FE] 지도 전체화면 버튼 동작 수정
  frontend/assets/css/map.css
  frontend/assets/js/maps/map.js
  frontend/index.html
Labels: FE

#80 [FE] 회원가입, 로그인 시 405 에러가 발생하는 문제 수정
  frontend/assets/html/login.html
  frontend/assets/html/signup.html
Labels: FE

#82 배포 환경에서 발생한 문제 수정
  everyplace/app/settings.py
  everyplace/board/views.py
  everyplace/pin/views.py
  everyplace/user/views.py
  frontend/assets/css/map.css
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/user_info.html
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/data.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/map.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/maps/pinDetail.js
  frontend/assets/js/maps/search.js
  frontend/assets/js/request/content.js
  frontend/index.html
Labels: FE, BE

#84 [BE] 보드 태그 관련 에러 해결
  everyplace/board/views.py
Labels: BE

#91 [FE] [BE] 보드 전체 목록 비공개보드 처리 및 UX, UI 개선
  everyplace/board/views.py
  frontend/assets/html/board_detail.html
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/boardDetail.js
Labels: FE, BE

#98 실시간 알림 환경 세팅 및 보드 댓글 알림 기능 구현
  everyplace/app/asgi.py
  everyplace/app/settings.py
  everyplace/board/consumers.py
  everyplace/board/routing.py
  everyplace/poetry.lock
  everyplace/pyproject.toml
  frontend/assets/js/maps/websocket.js
  frontend/index.html
Labels: FE, BE

#102 실시간 알림을 관리하는 앱, 모델 생성 및 알림 리스트 조회 기능 구현
  everyplace/app/asgi.py
  everyplace/app/settings.py
  everyplace/app/urls.py
  everyplace/notification/__init__.py
  everyplace/notification/admin.py
  everyplace/notification/apps.py
  everyplace/notification/consumers.py
  everyplace/notification/migrations/0001_initial.py
  everyplace/notification/migrations/__init__.py
  everyplace/notification/models.py
  everyplace/notification/routing.py
  everyplace/notification/serializers.py
  everyplace/notification/tests.py
  everyplace/notification/urls.py
  everyplace/notification/views.py
  everyplace/user/migrations/0003_alter_user_profile_img.py
Labels: BE

#106 알림 리스트 페이지 및 내부 기능 구현
  everyplace/notification/consumers.py
  everyplace/notification/migrations/0002_notification_related_url.py
  everyplace/notification/models.py
  everyplace/notification/serializers.py
  frontend/assets/html/notification.html
Labels: FE, BE

#108 알림 읽음 여부에 따른 처리
  everyplace/notification/serializers.py
  everyplace/notification/urls.py
  everyplace/notification/views.py
  frontend/assets/css/pin-list.css
  frontend/assets/html/notification.html
  frontend/assets/js/maps/websocket.js
  frontend/index.html
Labels: FE, BE

#111 세 가지 실시간 알림 기능 구현
  everyplace/notification/consumers.py
  frontend/assets/html/notification.html
Labels: FE, BE

#115 알림 삭제 기능 구현 및 알림 관련 UI 수정
  everyplace/notification/consumers.py
  everyplace/notification/serializers.py
  everyplace/notification/urls.py
  everyplace/notification/views.py
  frontend/assets/css/pin-list.css
  frontend/assets/html/notification.html
  frontend/assets/js/maps/websocket.js
  frontend/index.html
Labels: FE, BE

#120 Pin, Notification 앱 API 명세 작성 및 관련된 기존 코드 수정
  everyplace/notification/views.py
  everyplace/pin/serializers.py
  everyplace/pin/urls.py
  everyplace/pin/views.py
Labels: BE

#119 [FE] [BE] 특정 유저가 좋아요한 보드 목록 조회 기능, 보드 목록 정렬 기능 추가, 예외처리 및 작은 에러나 세부 요소 코드 수정
  everyplace/app/middleware.py
  everyplace/app/settings.py
  everyplace/board/serializers.py
  everyplace/board/views.py
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/js/maps/boardDetail.js
Labels: FE, BE

#125 UserSerializer 기능 분리 완료
  everyplace/board/views.py
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/event.js
Labels: FE, BE

#126 메인페이지 리팩토링 작업 완료
  everyplace/app/middleware.py
  everyplace/app/settings.py
  everyplace/user/views.py
  frontend/assets/css/index.css
  frontend/assets/css/map.css
  frontend/assets/html/board_detail.html
  frontend/assets/html/follower.html
  frontend/assets/html/following.html
  frontend/assets/html/login.html
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/profile_edit.html
  frontend/assets/html/signup.html
  frontend/assets/html/tagged_board_list.html
  frontend/assets/html/user_info.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/js/maps/board.js
  frontend/assets/js/maps/event.js
  frontend/assets/js/maps/index.js
  frontend/assets/js/maps/pin.js
  frontend/assets/js/maps/websocket.js
  frontend/assets/js/request/content.js
  frontend/assets/js/util/boardCreateModal.js
  frontend/assets/js/util/boardSlide.js
  frontend/assets/js/util/footer.js
  frontend/assets/js/util/header.js
  frontend/assets/js/util/pinDetailModal.js
  frontend/assets/js/util/preloader.js
  frontend/assets/js/util/responsive.js
  frontend/index.html
Labels: FE, BE

#127 [FE] [BE] 코드 최신화 이후 발생한 문제 수정
  everyplace/board/serializers.py
  frontend/assets/html/notification.html
  frontend/assets/html/pin_list.html
  frontend/assets/html/signup.html
  frontend/assets/html/tagged_board_list.html
  frontend/assets/html/user_liked_board.html
  frontend/assets/html/user_tagged_board.html
  frontend/assets/js/maps/boardDetail.js
  frontend/assets/js/maps/event.js
Labels: FE, BE
